from .base_task import Task
from .dummy import DummyTask
from .elementary_math_qa import ElementaryMathQA
from .gsm8k import GSM8K
from .mbpp import MBPP
from .mmlu import MMLUTask
from .triviaqa import TriviaQA
from .math import MATH
from .imdb import IMDB
from .anthropic_hh import AnthropicHH
from .tldr import TLDR
